### ISSUE TITLE
@todo 1.0

### ISSUE THREAD

**Issue by sergeyklay** [gleez/cms#169]
Part of Gleez 1.0 milestone
- [x] Add Gravatar support #482
- [x] Full oAuth2 / SSO support
- [ ] More themes (minimum 2-3)
- [ ] Media library support (similar WP media library) with file drag support
- [ ] Visual Widget constructor/generator with more option (not only static)
- [x] Gleez Editor with full wysiwygs support #238 #214
- [x] Complete blog system for users  #312 #316
- [x] Contact form #295
- [ ] Internal correspondence users
- [ ] The rating system
- [x] Slider #126
- [ ] Polls
- [x] Full user profile with multiple fields
- [x] Minimum (At least) API documentation
- [x] Working and a full demo site http://demo.gleezcms.org
- [x] Roadmap [milestone](https://github.com/gleez/cms/issues?milestone=1&page=1&state=open)
- [ ] Gleez Forum Module
- [ ] News(RSS/Activity) Widget
- [ ] Gleez Cart Module
- [ ] Gleez Shop Module
- [ ] Support many popular payments system
- [x] RSS #289, #290, #292, #293 #294, #404, #414, #418, #420
- [x] Corporate Blog [Gleez CMS Blog](http://gleezcms.org/blog)
- [ ] [Verify.js](http://verifyjs.com/) &mdash; A powerful, customizable asynchronous form validation library
- [ ] Add an event auto-hide each messages with nice effect if user does not close it
- [x] Page with permission by roles/users

This year we plan to implement most of these things.
I want to offer you to choose something from the list, the most needed now.

**Comment by sergeyklay** [comment]
@sandeepone Unfortunately I could not find enough free time for this. I want to close this issue because I don't want a bunch of these lying around.  If anyone wants to get started, I'd love that.
